### ISSUE TITLE
ERROR:  Sorry!  We could not load this pack.  Received error: [object Object]

### ISSUE THREAD

**Issue by sw90036** [omaha-consulting/winstall#162] opened 2024-03-06 09:55 UTC
I just created a new pack with ~25 apps and when I attempt to view the pack I get this error:

> Sorry! We could not load this pack.
> Recieved error: [object Object]

This happens every time.  I am using MS Edge on Windows 11 and also get the same error with Chrome.

I did a Google search and found another post with this same error message here -
https://community.brave.com/t/winstall-website-page-loading-errors/397198

Any ideas?

THANKS!

**Comment by mherrmann** [comment] 2024-03-06 09:57
Duplicate of #154.

**Closed by mherrmann** 2024-03-06 09:57 UTC
