### ISSUE TITLE
Packs don't work

### ISSUE THREAD

**Issue by BenignPigeon** [omaha-consulting/winstall#163] opened 2024-03-17 10:21 UTC
Packs just don't work, creating packs, editing packs or viewing packs.
When I click on view pack it just doesn't work. It does this for every pack I try to click on. 
This is also the case when I try to view my own packs as well.

![image](https://github.com/omaha-consulting/winstall/assets/85837722/1bf3e314-dbcd-408a-ba36-24e174267b39)

![image](https://github.com/omaha-consulting/winstall/assets/85837722/969130ae-7367-4d2f-9893-22332ede9b17)

![image](https://github.com/omaha-consulting/winstall/assets/85837722/714e5f8d-10ca-49dd-aac4-052bd53068eb)

![image](https://github.com/omaha-consulting/winstall/assets/85837722/39022452-49c0-4776-b888-f8086b6a130a)

**Comment by mherrmann** [comment] 2024-03-17 14:28
Thank you for the report. I'm closing this as a duplicate of #154.

**Closed by mherrmann** 2024-03-17 14:28 UTC
