### ISSUE TITLE
Objet error

### ISSUE THREAD

**Issue by cl0v3r13** [omaha-consulting/winstall#158] opened 2024-01-08 14:06 UTC
When opening an application package, Object Object error is displayed.

![Captura de pantalla 2024-01-08 150555](https://github.com/omaha-consulting/winstall/assets/47293977/2458e7bf-dabc-47cd-8f64-6126f7446eda)

**Comment by mherrmann** [comment] 2024-01-08 14:16
Duplicate of #154.

**Closed** 2024-01-08 14:17 UTC
