### ISSUE TITLE
Sorry! We could not load this pack

### ISSUE THREAD

**Issue by webysther** [omaha-consulting/winstall#161] opened 2024-01-24 08:43 UTC
I got this error for all packs:

![image](https://github.com/omaha-consulting/winstall/assets/750007/215033df-869e-4ad2-8287-8acafdf1967c)

Example: https://winstall.app/packs/qO_m22F6k

**Comment by mherrmann** [comment] 2024-01-24 08:50
This is a duplicate of #154.

**Closed by mherrmann** 2024-01-24 08:50 UTC
